name: Dental Clinic ERP - CI Build & Test
permissions:
  contents: read

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]
  workflow_dispatch: 

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository code
    - name: Checkout Code
      uses: actions/checkout@v7

    # Setup .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: '10.0.x' 

    # Restore NuGet Packages
    - name: Restore Dependencies
      run: dotnet restore DentalClinicERPSystem.slnx
      working-directory: DentalClinicERPSystem/

    # Build Solution
    - name: Build Solution
      run: dotnet build DentalClinicERPSystem.slnx --configuration Release --no-restore
      working-directory: DentalClinicERPSystem/

    #  Upload Web App
    - name: Upload Web App
      run: dotnet publish Web/Web.csproj -c Release -o ./publish --no-build
      working-directory: DentalClinicERPSystem/

    # Step 7: Upload Build Artifacts
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: web-app-build
        path: ./publish
